name: Quality check

on:
  push:
    branches-ignore:
      - master

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Dependency instalation
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Typescript check
        run: npm run ts-check

      - name: Integration tests
        run: npm test

      - name: Building and run docker container
        # We modify the PORT env to be sure that we still allow to modify our docker container's port
        run: |
          docker build . -t proxy-image
          docker run -d -p 3000:1000 --env="PORT=1000" proxy-image
          sleep 5

      - name: Check if service is up
        run: curl "http://localhost:3000" &>/dev/null && echo OK || exit 1
